
name: C/C++ Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    
    name: cppcheck
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: CppCheck ocde
      run: cppcheck 3_Implementation 
